use_frameworks!

platform :ios, '8.0'

target 'CRJCGContextObject_Example' do
  pod 'CRJCGContextObject', :path => '../'

  target 'CRJCGContextObject_Tests' do
    inherit! :search_paths

    
  end
end
